eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  error:
    include-stacktrace: never
  port: ${PORT:0}
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: discountApi
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/discountdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
